spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 367e3d5858dc10db2023
            client-secret: a7a0364fc3f9f23316d40940342103bf3b4db0ab
            redirect_uri: http://localhost:8080/login/oauth2/code/github
            scope: user